name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Mech
        uses: actions/checkout@v2
        with:
          path: mech
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/mech:/mech ivydl/ivy-mech:latest python3 -m pytest ivy_mech_tests/
