name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Mech
        uses: actions/checkout@v2
        with:
          path: mech
          persist-credentials: false

      - name: Run Tests
        run: |
          cd mech
          docker run --rm -it -v `pwd`:/mech unifyai/mech:latest python3 -m pytest ivy_mech_tests/
